function datareport1 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DATAREPORT1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  DATAREPORT1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  datareport1 = importfile("C:\Users\jhurtado5179\Documents\GitHub\Alvarado-Creek-\Alvarado Creek Data\August Data\data_report_11-05-2024_13-24-11.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Nov-2024 13:47:39

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["datetime", "TryptophanRFU", "CDOMRFU", "Temperature"];
opts.VariableTypes = ["datetime", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "datetime", "InputFormat", "MM/dd/yyyy HH:mm");

% Import the data
datareport1 = readtable(filename, opts);

end