function USGSsep = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  USGSAUG = IMPORTFILE(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  USGSAUG = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  USGSAUG = IMPORTFILE(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  USGSAug = importfile("C:\Users\jhurtado5179\Documents\GitHub\Alvarado-Creek-\Alvarado Creek Data\August Data\USGSAug.xlsx", "Sheet1", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Nov-2024 13:37:16

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["datetime", "height"];
opts.VariableTypes = ["datetime", "double"];

% Import the data
USGSsep = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    USGSsep = [USGSsep; tb]; %#ok<AGROW>
end

end